services:
  navidrome-bpm-plugin:
    build: .
    image: navidrome-bpm-plugin:local
    container_name: navidrome-bpm-plugin
    restart: unless-stopped
    volumes:
      - ./config:/config
      - /DATA/Media/Music:/music:ro
    environment:
      NBDPM_NAVIDROME_URL: http://navidrome:4533
      NBDPM_NAVIDROME_USERNAME: washbasin6779
      NBDPM_NAVIDROME_PASSWORD: OoGPC9mvB80Zfa
      NBDPM_MUSICDIR: /music
      NBDPM_NAVIDROME_MUSICDIR: /music
      NBDPM_CACHE_PATH: /config/cache.sqlite
    networks:
      - navidrome_default

networks:
  navidrome_default:
    external: true
