services:
  navidrome-bpm-plugin:
    build: .
    image: navidrome-bpm-plugin:local
    container_name: navidrome-bpm-plugin
    restart: unless-stopped
    volumes:
      - ./config:/config
      - /DATA/Media/Music:/music:ro
    env_file:
      - .env
    networks:
      - navidrome_default

networks:
  navidrome_default:
    external: true
