navidrome:
  url: http://192.168.178.103:4533
  username: washbasin6779
  password: OoGPC9mvB80Zfa

musicDir: /music

cache:
  path: /config/cache.sqlite

analysis:
  detector: essentia
  workers: 6

playlist:
  bucketSize: 10
  minimum: 60
  maximum: 220
  deleteEmpty: false
  includeOutOfRange: false

scan:
  interval: 30m

metadata:
  writeTags: false
  rescanAfterWrite: false
